### PR TITLE
Added bower.json

### PR DESCRIPTION
**Pull request by dstulle**
I added a bower.json to be able to use this as a module in bower.

### CODE REVIEW

**Comment by binarymist** [comment]
This looks like quite a useful project, any chance that you will be maintaining it in the near future? If not, I'll fork.
Thanks.

**Comment by dstulle** [comment]
Do you mean the project or my pull request? The project looks abandoned since 2016 and my pull request hangs here since 2017 so I do not expect something will happen soon.

**Comment by eloyz** [comment]
I feel horrible, I thought people weren't interested and moved on.

**Comment by binarymist** [comment]
I liked your API, but sadly this targets the browser and I needed to target node server and client side, so rewrote/ported https://www.npmjs.com/package/mocksse

**Comment by eloyz** [comment]
@binarymist I appreciate the acknowledgements, thank you so much. 👍🏼

**Pull request merged**
